/*
 ** creeated by GF on 2017.11.27
 ** 文件：pid组件配置
 **
 */
(function(window) {
    var shapeAttr = ['text', 'textSize', 'textFamily', 'textColor', 'bitNumber', 'text2Size', 'text2Family', 'text2Color', 'magnification'];
    var textAttr = ['text', 'textSize', 'textFamily', 'textColor'];
    var lineAttr = ['color', 'stroke-width', 'length', 'textSize', 'textFamily', 'textColor', 'diameter', 'text2Size', 'text2Family', 'text2Color'];
    // var pointAttr = ['线色、填充颜色、边径粗细、宽、高'];
    var pointAttr = ['width', 'height', 'linecolor', 'fillColor', 'edgeBorder'];
    // window.stateMap = {
    //     //基本原件
    //     '000': '正常',
    //     '001': '开启', //黑边透明
    //     '002': '关闭', //红边透明
    // };
    window.facilityConfig = {
        'FACILITY_BAV': { //01
            name: '球阀',
            facilityType: 'FACILITY_BAV',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape01_001.svg',
            iconWidth: 36,
            iconHeight: 18,
            svgWidth: 36,
            svgHeight: 18,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_GAV': { //02
            name: '闸阀',
            facilityType: 'FACILITY_GAV',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape02_001.svg',
            iconWidth: 36,
            iconHeight: 18,
            svgWidth: 36,
            svgHeight: 18,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_GLV': { //03
            name: '截止阀',
            facilityType: 'FACILITY_GLV',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape03_001.svg',
            iconWidth: 36,
            iconHeight: 18,
            svgWidth: 36,
            svgHeight: 18,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_THV': { //04
            name: '节流阀',
            facilityType: 'FACILITY_THV',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape04_001.svg',
            iconWidth: 36,
            iconHeight: 18,
            svgWidth: 36,
            svgHeight: 18,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_FM': { //05
            name: '超声波流量计',
            facilityType: 'FACILITY_FM',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape05_001.svg',
            iconWidth: 36,
            iconHeight: 18,
            svgWidth: 36,
            svgHeight: 18,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_FA': { //06
            name: '阻火器',
            facilityType: 'FACILITY_FA',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape06_001.svg',
            iconWidth: 36,
            iconHeight: 18,
            svgWidth: 36,
            svgHeight: 18,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_BUV': { //07
            name: '蝶阀',
            facilityType: 'FACILITY_BUV',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape07_001.svg',
            iconWidth: 36,
            iconHeight: 18,
            svgWidth: 36,
            svgHeight: 18,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_CHV': { //08
            name: '止回阀',
            facilityType: 'FACILITY_CHV',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape08_001.svg',
            iconWidth: 36,
            iconHeight: 18,
            svgWidth: 36,
            svgHeight: 18,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_NV': { //09
            name: '针形阀',
            facilityType: 'FACILITY_NV',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape09_001.svg',
            iconWidth: 35,
            iconHeight: 35,
            svgWidth: 35,
            svgHeight: 35,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_SV': { //10
            name: '二阀组',
            facilityType: 'FACILITY_SV',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape10_001.svg',
            iconWidth: 35,
            iconHeight: 35,
            svgWidth: 35,
            svgHeight: 35,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_PSV': { //11
            name: '安全阀',
            facilityType: 'FACILITY_PSV',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape11_001.svg',
            iconWidth: 35,
            iconHeight: 35,
            svgWidth: 35,
            svgHeight: 35,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_FV': { //12
            name: '五阀组',
            facilityType: 'FACILITY_FV',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape12_001.svg',
            iconWidth: 35,
            iconHeight: 35,
            svgWidth: 35,
            svgHeight: 35,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_FXC': { //13
            name: '调压器',
            facilityType: 'FACILITY_FXC',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape13_001.svg',
            iconWidth: 35,
            iconHeight: 35,
            svgWidth: 35,
            svgHeight: 35,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_ZS': { //14
            name: '切断阀',
            facilityType: 'FACILITY_ZS',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape14_001.svg',
            iconWidth: 35,
            iconHeight: 35,
            svgWidth: 35,
            svgHeight: 35,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_EV': { //15
            name: '电动球阀',
            facilityType: 'FACILITY_EV',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape15_001.svg',
            iconWidth: 35,
            iconHeight: 65.83,
            svgWidth: 35,
            svgHeight: 65.83,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_ELV': { //16
            name: '电液联动阀',
            facilityType: 'FACILITY_ELV',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape16_001.svg',
            iconWidth: 35,
            iconHeight: 65.83,
            svgWidth: 35,
            svgHeight: 65.83,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_FC': { //17
            name: '流量调节阀',
            facilityType: 'FACILITY_FC',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape17_001.svg',
            iconWidth: 35,
            iconHeight: 35,
            svgWidth: 35,
            svgHeight: 35,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_E': { //18
            name: '换热器',
            facilityType: 'FACILITY_E',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape18_001.svg',
            iconWidth: 35,
            iconHeight: 65.83,
            svgWidth: 35,
            svgHeight: 65.83,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_FEBO': { //19
            name: '8字盲板(开启)',
            facilityType: 'FACILITY_FEBO',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape19_001.svg',
            iconWidth: 35,
            iconHeight: 65.83,
            svgWidth: 35,
            svgHeight: 65.83,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_FEBC': { //20
            name: '8字盲板(关闭)',
            facilityType: 'FACILITY_FEBC',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape20_001.svg',
            iconWidth: 35,
            iconHeight: 65.83,
            svgWidth: 35,
            svgHeight: 65.83,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_M': { //21
            name: '汇管',
            facilityType: 'FACILITY_M',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape21_001.svg',
            iconWidth: 35,
            iconHeight: 10,
            svgWidth: 83,
            svgHeight: 20,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_PL': { //22
            name: '清球发射器',
            facilityType: 'FACILITY_PL',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape22_001.svg',
            iconWidth: 35,
            iconHeight: 10,
            svgWidth: 83,
            svgHeight: 20,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_EU': { //23
            name: 'U形换热器',
            facilityType: 'FACILITY_EU',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape23_001.svg',
            iconWidth: 35,
            iconHeight: 11,
            svgWidth: 83,
            svgHeight: 24,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_F': { //24
            name: '卧式过滤器',
            facilityType: 'FACILITY_F',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape24_001.svg',
            iconWidth: 35,
            iconHeight: 20,
            svgWidth: 42,
            svgHeight: 24,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_IJ': { //25
            name: '绝缘接头',
            facilityType: 'FACILITY_IJ',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape25_001.svg',
            iconWidth: 20,
            iconHeight: 35,
            svgWidth: 20,
            svgHeight: 35,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_FST': { //26
            name: '放散塔',
            facilityType: 'FACILITY_FST',
            geometryType: 'GEOMETRY_POLYLINE',
            url: 'image/tools_icon3/shape26_001.svg',
            iconWidth: 25,
            iconHeight: 87,
            svgWidth: 24,
            svgHeight: 83,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'LINE_BLACK_BOLD': { //27
            name: '实线',
            facilityType: 'LINE_BLACK_BOLD',
            geometryType: 'GEOMETRY_LINE',
            lineType: 'StraightLine',
            url: 'image/tools_icon3/shape27_001.svg',
            iconWidth: 35,
            iconHeight: 35,
            svgWidth: 80,
            svgHeight: 40,
            state: ['000'],
            attribute: lineAttr, //元件属性数组中的排列顺序
        },
        'LINE_CONNECTIONLINE': { //33
            name: '虚线',
            facilityType: 'LINE_CONNECTIONLINE',
            geometryType: 'GEOMETRY_LINE',
            lineType: 'StraightLine',
            url: 'image/tools_icon3/shape33_001.svg',
            iconWidth: 35,
            iconHeight: 35,
            svgWidth: 80,
            svgHeight: 40,
            state: ['000'],
            dasharray: ['--'],
            attribute: lineAttr, //元件属性数组中的排列顺序
        },
        'LINE_ACTUALBROKENLINE': { //76
            name: '实折线',
            facilityType: 'LINE_ACTUALBROKENLINE',
            geometryType: 'GEOMETRY_POLYLINE',
            lineType: 'BrokenLine',

            url: 'image/tools_icon3/shape76_001.svg',
            iconWidth: 35,
            iconHeight: 35,
            svgWidth: 80,
            svgHeight: 40,
            state: ['000'],
            attribute: lineAttr, //元件属性数组中的排列顺序
        },
        'LINE_IMAGINARYFOLDLINE': { //77
            name: '虚折线',
            facilityType: 'LINE_IMAGINARYFOLDLINE',
            geometryType: 'GEOMETRY_POLYLINE',
            lineType: 'BrokenLine',
            url: 'image/tools_icon3/shape77_001.svg',
            iconWidth: 35,
            iconHeight: 35,
            svgWidth: 80,
            svgHeight: 40,
            state: ['000'],
            dasharray: ['--'],
            attribute: lineAttr, //元件属性数组中的排列顺序
        },
        'LINE_WIRE': { //34
            name: '跨接线',
            facilityType: 'LINE_WIRE',
            geometryType: 'GEOMETRY_CURVELINE',
            url: 'image/tools_icon3/shape34_001.svg',
            iconWidth: 35,
            iconHeight: 35,
            svgWidth: 80,
            svgHeight: 40,
            state: ['000'],
            attribute: lineAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_CABLECONNECTION': { //35
            name: '连接点',
            facilityType: 'FACILITY_CABLECONNECTION',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape35_001.svg',
            iconWidth: 14,
            iconHeight: 14,
            svgWidth: 14,
            svgHeight: 14,
            state: ['000'],
            attribute: [], //元件属性数组中的排列顺序
        },
        'FACILITY_SOLIDPOINT': { //78
            name: '连接点',
            facilityType: 'FACILITY_SOLIDPOINT',
            geometryType: 'GEOMETRY_POLYGON',
            shapeType: 'SHAPE_ELLIPSE',
            url: 'image/tools_icon3/shape78_001.svg',
            iconWidth: 14,
            iconHeight: 14,
            svgWidth: 4,
            svgHeight: 4,
            state: ['000'],
            attribute: pointAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_CREATETEXT': { //79
            name: '文字',
            facilityType: 'FACILITY_CREATETEXT',
            geometryType: 'GEOMETRY_TEXT',
            url: 'image/tools_icon3/shape79_001.svg',
            iconWidth: 35,
            iconHeight: 35,
            svgWidth: 35,
            svgHeight: 35,
            state: ['000'],
            attribute: textAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_CYAN_MARK': { //37
            name: '仪表1',
            facilityType: 'FACILITY_CYAN_MARK',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape37_001.svg',
            iconWidth: 35,
            iconHeight: 35,
            svgWidth: 35,
            svgHeight: 35,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_RED_MARK': { //38
            name: '仪表2',
            facilityType: 'FACILITY_RED_MARK',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape38_001.svg',
            iconWidth: 35,
            iconHeight: 35,
            svgWidth: 35,
            svgHeight: 35,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_LEFT_MARK1': { //39
            name: '指向标1',
            facilityType: 'FACILITY_LEFT_MARK1',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape39_001.svg',
            iconWidth: 40,
            iconHeight: 20.23,
            svgWidth: 40,
            svgHeight: 20.23,
            state: ['000'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_RIGHT_MARK2': { //40
            name: '指向标4',
            facilityType: 'FACILITY_RIGHT_MARK2',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape40_001.svg',
            iconWidth: 40,
            iconHeight: 20.23,
            svgWidth: 40,
            svgHeight: 20.23,
            state: ['000'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_MARK': { //41
            name: '工艺参数节点',
            facilityType: 'FACILITY_MARK',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape41_001.svg',
            iconWidth: 35,
            iconHeight: 35,
            svgWidth: 35,
            svgHeight: 35,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_TRIANGLE_MARK': { //42
            name: '待定',
            facilityType: 'FACILITY_TRIANGLE_MARK',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape42_001.svg',
            iconWidth: 35,
            iconHeight: 35,
            svgWidth: 35,
            svgHeight: 35,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_GROUND': { //43
            name: '法兰盲板',
            facilityType: 'FACILITY_GROUND',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape43_001.svg',
            iconWidth: 35,
            iconHeight: 35,
            svgWidth: 35,
            svgHeight: 35,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_TRIANGLE': { //44
            name: '异径管',
            facilityType: 'FACILITY_TRIANGLE',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape44_001.svg',
            iconWidth: 26,
            iconHeight: 26,
            svgWidth: 26,
            svgHeight: 26,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_RIGHT_MARK1': { //47
            name: '指向标2',
            facilityType: 'FACILITY_RIGHT_MARK1',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape47_001.svg',
            iconWidth: 40,
            iconHeight: 20.23,
            svgWidth: 40,
            svgHeight: 20.23,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_LEFT_MARK2': { //48
            name: '指向标3',
            facilityType: 'FACILITY_LEFT_MARK2',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape48_001.svg',
            iconWidth: 40,
            iconHeight: 20.23,
            svgWidth: 40,
            svgHeight: 20.23,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_SHAPE1': { //49
            name: '待定',
            facilityType: 'FACILITY_SHAPE1',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape49_001.svg',
            iconWidth: 35,
            iconHeight: 17,
            svgWidth: 35,
            svgHeight: 17,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_SHAPE2': { //50
            name: '待定',
            facilityType: 'FACILITY_SHAPE2',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape50_001.svg',
            iconWidth: 35,
            iconHeight: 17,
            svgWidth: 35,
            svgHeight: 17,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_SHAPE3': { //51
            name: '待定',
            facilityType: 'FACILITY_SHAPE3',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape51_001.svg',
            iconWidth: 35,
            iconHeight: 35,
            svgWidth: 35,
            svgHeight: 35,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_SHAPE4': { //52
            name: '汇管',
            facilityType: 'FACILITY_SHAPE4',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape52_001.svg',
            iconWidth: 25,
            iconHeight: 87,
            svgWidth: 30,
            svgHeight: 300,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_SHAPE53': { //53
            name: '待定',
            facilityType: 'FACILITY_SHAPE53',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape53_001.svg',
            iconWidth: 87,
            iconHeight: 16,
            svgWidth: 912,
            svgHeight: 140,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_SHAPE54': { //54
            name: '加臭装置',
            facilityType: 'FACILITY_SHAPE54',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape54_001.svg',
            iconWidth: 35,
            iconHeight: 72,
            svgWidth: 64,
            svgHeight: 72,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_SHAPE55': { //55
            name: '待定',
            facilityType: 'FACILITY_SHAPE55',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape55_001.svg',
            iconWidth: 35,
            iconHeight: 72,
            svgWidth: 64,
            svgHeight: 72,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_SHAPE57': { //57
            name: '无泄漏磁力驱动泵',
            facilityType: 'FACILITY_SHAPE57',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape57_001.svg',
            iconWidth: 35,
            iconHeight: 38,
            svgWidth: 26,
            svgHeight: 38,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_SHAPE58': { //58
            name: '球阀',
            facilityType: 'FACILITY_SHAPE58',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape58_001.svg',
            iconWidth: 35,
            iconHeight: 38,
            svgWidth: 27,
            svgHeight: 38,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_SHAPE59': { //59
            name: '针阀',
            facilityType: 'FACILITY_SHAPE59',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape59_001.svg',
            iconWidth: 35,
            iconHeight: 38,
            svgWidth: 27,
            svgHeight: 38,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_SHAPE60': { //60
            name: '法兰式二阀组',
            facilityType: 'FACILITY_SHAPE60',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape60_001.svg',
            iconWidth: 35,
            iconHeight: 38,
            svgWidth: 27,
            svgHeight: 38,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_SHAPE61': { //61
            name: '法兰式针阀',
            facilityType: 'FACILITY_SHAPE61',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape61_001.svg',
            iconWidth: 35,
            iconHeight: 38,
            svgWidth: 27,
            svgHeight: 38,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_SHAPE62': { //62
            name: '气体涡轮流量计',
            facilityType: 'FACILITY_SHAPE62',
            geometryType: 'GEOMETRY_POLYLINE',
            url: 'image/tools_icon3/shape62_001.svg',
            iconWidth: 35,
            iconHeight: 38,
            svgWidth: 76,
            svgHeight: 38,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_ARROW63': { //63
            name: '气流方向黑',
            facilityType: 'FACILITY_ARROW63',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape63_001.svg',
            iconWidth: 25,
            iconHeight: 25,
            svgWidth: 25,
            svgHeight: 25,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_ARROW64': { //64
            name: '气流方向红',
            facilityType: 'FACILITY_ARROW64',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape64_001.svg',
            iconWidth: 25,
            iconHeight: 25,
            svgWidth: 25,
            svgHeight: 25,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_ARROW65': { //65
            name: '气流方向绿',
            facilityType: 'FACILITY_ARROW65',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape65_001.svg',
            iconWidth: 25,
            iconHeight: 25,
            svgWidth: 25,
            svgHeight: 25,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_ARROW66': { //66
            name: '气流方向蓝',
            facilityType: 'FACILITY_ARROW66',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape66_001.svg',
            iconWidth: 25,
            iconHeight: 25,
            svgWidth: 25,
            svgHeight: 25,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_ARROW67': { //67
            name: '气流方向黄',
            facilityType: 'FACILITY_ARROW67',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape67_001.svg',
            iconWidth: 25,
            iconHeight: 25,
            svgWidth: 25,
            svgHeight: 25,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_ARROW68': { //68
            name: '气流方向紫',
            facilityType: 'FACILITY_ARROW68',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape68_001.svg',
            iconWidth: 25,
            iconHeight: 25,
            svgWidth: 25,
            svgHeight: 25,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_ARROW69': { //69
            name: '气流方向青',
            facilityType: 'FACILITY_ARROW69',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape69_001.svg',
            iconWidth: 25,
            iconHeight: 25,
            svgWidth: 25,
            svgHeight: 25,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        'FACILITY_ARROW70': { //70
            name: '气流方向透明',
            facilityType: 'FACILITY_ARROW70',
            geometryType: 'GEOMETRY_POLYGON',
            url: 'image/tools_icon3/shape70_001.svg',
            iconWidth: 25,
            iconHeight: 25,
            svgWidth: 25,
            svgHeight: 25,
            state: ['001', '002'],
            attribute: shapeAttr, //元件属性数组中的排列顺序
        },
        // 'FACILITY_ARROW75': { //75
        //     name: '灯泡',
        //     facilityType: 'FACILITY_ARROW75',
        //     geometryType: 'GEOMETRY_POLYGON',
        //     url: 'image/tools_icon3/shape75_001.svg',
        //     iconWidth: 25,
        //     iconHeight: 25,
        //     svgWidth: 18,
        //     svgHeight: 35,
        //     state: ['005', '006','007'],
        //     attribute: shapeAttr, //元件属性数组中的排列顺序
        // },
    };
})(window);